const PlaylistsActionTypes = {
  FETCH_PLAYLISTS_START: "FETCH_PLAYLISTS_START",
  FETCH_PLAYLISTS_SUCCESS: "FETCH_PLAYLISTS_SUCCESS",
  FETCH_PLAYLISTS_FAILURE: "FETCH_PLAYLISTS_FAILURE",
};

export default PlaylistsActionTypes;
