const PlaylistActionTypes = {
  FETCH_PLAYLIST_START: "FETCH_PLAYLIST_START",
  FETCH_PLAYLIST_SUCCESS: "FETCH_PLAYLIST_SUCCESS",
  FETCH_PLAYLIST_FAILURE: "FETCH_PLAYLIST_FAILURE",
};

export default PlaylistActionTypes;
