const BrowseActionTypes = {
  // New Releases
  FETCH_NEW_RELEASES_START: "FETCH_NEW_RELEASES_START",
  FETCH_NEW_RELEASES_SUCCESS: "FETCH_NEW_RELEASES_SUCCESS",
  FETCH_NEW_RELEASES_FAILURE: "FETCH_NEW_RELEASES_FAILURE",
};

export default BrowseActionTypes;
