const SearchActionTypes = {
  // Search Albums
  FETCH_SEARCH_ALBUMS_START: "FETCH_SEARCH_ALBUMS_START",
  FETCH_SEARCH_ALBUMS_SUCCESS: "FETCH_SEARCH_ALBUMS_SUCCESS",
  FETCH_SEARCH_ALBUMS_FAILURE: "FETCH_SEARCH_ALBUMS_FAILURE",
};

export default SearchActionTypes;
